"""entries table

Revision ID: 3a2cc5880fea
Revises: 
Create Date: 2020-09-14 18:03:18.535753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a2cc5880fea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('date_of_creation', sa.Text(), nullable=False),
    sa.Column('company_name', sa.Text(), nullable=False),
    sa.Column('owner_name', sa.Text(), nullable=False),
    sa.Column('contact_no', sa.Text(), nullable=False),
    sa.Column('email_address', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry')
    # ### end Alembic commands ###
